// <auto-generated />
using System;
using CPAM.GestionDossiers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPAM.GestionDossiers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817200908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPAM.GestionDossiers.Models.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaires")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantRembourse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomAssure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PourcentageRemboursement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dossiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentResponsable = "Alice Martin",
                            Categorie = "Santé",
                            Commentaires = "Dossier en cours de traitement.",
                            DateCreation = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDerniereModification = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1985, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontantRembourse = 150.00m,
                            NomAssure = "Jean Dupont",
                            NumeroIdentite = "D123456",
                            PourcentageRemboursement = 75.00m,
                            Statut = "En cours"
                        },
                        new
                        {
                            Id = 2,
                            AgentResponsable = "Bob Lefevre",
                            Categorie = "Retraite",
                            Commentaires = "Dossier terminé avec succès.",
                            DateCreation = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDerniereModification = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1970, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontantRembourse = 200.00m,
                            NomAssure = "Marie Curie",
                            NumeroIdentite = "D654321",
                            PourcentageRemboursement = 100.00m,
                            Statut = "Terminé"
                        },
                        new
                        {
                            Id = 3,
                            AgentResponsable = "Claire Dubois",
                            Categorie = "Invalidité",
                            Commentaires = "En attente de documents supplémentaires.",
                            DateCreation = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDerniereModification = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontantRembourse = 0.00m,
                            NomAssure = "Pierre Martin",
                            NumeroIdentite = "D789012",
                            PourcentageRemboursement = 0.00m,
                            Statut = "En attente"
                        },
                        new
                        {
                            Id = 4,
                            AgentResponsable = "David Moreau",
                            Categorie = "Santé",
                            Commentaires = "Dossier en cours de traitement, attente de pièces justificatives.",
                            DateCreation = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDerniereModification = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1988, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontantRembourse = 300.00m,
                            NomAssure = "Sophie Durand",
                            NumeroIdentite = "D345678",
                            PourcentageRemboursement = 60.00m,
                            Statut = "En cours"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
