// <auto-generated />
using System;
using CPAM.GestionDossiers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPAM.GestionDossiers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250806150218_SeedDossiers")]
    partial class SeedDossiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPAM.GestionDossiers.Models.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomAssure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dossiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomAssure = "Jean Dupont",
                            NumeroDossier = "D123456",
                            Statut = "En cours"
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomAssure = "Marie Curie",
                            NumeroDossier = "D654321",
                            Statut = "Terminé"
                        },
                        new
                        {
                            Id = 3,
                            DateCreation = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomAssure = "Pierre Martin",
                            NumeroDossier = "D789012",
                            Statut = "En attente"
                        },
                        new
                        {
                            Id = 4,
                            DateCreation = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomAssure = "Sophie Durand",
                            NumeroDossier = "D345678",
                            Statut = "En cours"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
